language: node_js

node_js:
  - '10.13.0'

cache:
  directories:
    - node-modules

before_script:
  - npm install global @angular/cli

script:
  - sonar-scanner

branches:
  only:
    - develop

deploy:
  provider: heroku
  app: node-mongo-api-server
  on: develop
  api_key:
    secure: "YOUR ENCRYPTED API KEY"

addons:
  sonarcloud:
    organization: 'deepakjhaaa-github'
    token:
      secure: $SONAR_TOKEN

before_deploy: "echo 'ready?'"
