language: node_js

node_js:
  - '10.13.0'

cache:
  directories:
    - node-modules

script:
  - sonar-scanner

branches:
  only:
    - develop

deploy:
  provider: heroku
  app: node-mongo-api-server
  on: develop
  api_key:
    secure: $HEROKU_API_KEY

addons:
  sonarcloud:
    organization: 'deepakjhaaa-github'
    token:
      secure: $SONAR_TOKEN

before_deploy: "echo 'ready?'"
